version: "3.8"

services:
  frontend:
    build: ./prod
    volumes:
      - ./dist:/app
    ports:
      - "80:80"
  node:
    image: node:16-alpine
    working_dir: /app
    command: npm run start
    volumes:
      - ./dist:/app
    ports:
      - "3000:3000"
  logs:
    image: elastic/kibana:7.15.2
    ports:
      - "5601:5601"
    volumes:
      - ./logs:/var/lib/elasticsearch
